### ISSUE TITLE
FYI...

### ISSUE THREAD

**Issue by skmcloughlin** [learn-co-curriculum/displaying-has-many-through-rails-lab#11]
No big deal but the Doctor#index page referenced in step 2 of the instructions is not tested in the specs.

**Comment by maxwellbenton** [comment]
Thank you for providing feedback.

We are in the process of updating the materials in this section and will be rewriting this lesson to address the current issues.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced. 💙
