### ISSUE TITLE
solution branch empty

### ISSUE THREAD

**Issue by BuffaloRob** [learn-co-curriculum/displaying-has-many-through-rails-lab#12]
None of the important files are in the solution branch. There's no migrations, models, controllers, or views

**Comment by curiositypaths** [comment]
Thanks for reporting this issue. We're now aware of it and are tracking it in
#14.  We will add this to our internal work queue and
notify you when it is resolved.

We're closing this issue but invite you to follow progress at that URL.

-- Flatiron Curriculum Team
