### ISSUE TITLE
Solution file does not have solution.

### ISSUE THREAD

**Issue by byojelly** [learn-co-curriculum/displaying-has-many-through-rails-lab#13]
After passing the lab I wanted to review my code against the solution however the solution did not have completed code.

Thank you.

**Comment by curiositypaths** [comment]
Thanks for reporting this issue. We're now aware of it and are tracking it in
#14.  We will add this to our internal work queue and
notify you when it is resolved.

We're closing this issue but invite you to follow progress at that URL.

-- Flatiron Curriculum Team
