### ISSUE TITLE
Rspec feature test for appointment#show doesn't test for datetime 

### ISSUE THREAD

**Issue by tracdnguyen** [learn-co-curriculum/displaying-has-many-through-rails-lab#15]
"Create an Appointment#show page that shows the **date**, **time**, patient, and doctor for that particular appointment. Note that there should NOT be an Appointment#index page –– we don't want to have all of the appointments on display for anyone to see."

`  it "should display an appointment's doctor" do
    visit appointment_path(@appointment)
    expect(page).to have_link("Hawkeye Pierce", href: doctor_path(@hawkeye))
  end

  it "should display an appointment's patient" do
    visit appointment_path(@appointment)
    expect(page).to have_link("Homer Simpson", href: patient_path(@homer))
  end

  it "should not have an index page" do
    expect {visit('/appointments')}.to raise_error(ActionController::RoutingError)
  end`

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.
We have updated the materials and believe your issue to have been resolved.
Thanks for your contribution! 💙
