### ISSUE TITLE
Solution branch still empty

### ISSUE THREAD

**Issue by atxrenegade** [learn-co-curriculum/displaying-has-many-through-rails-lab#17]
Solution branch still empty - first reported Dec. 17, 2017. Closed but not resolved.

**Comment by jenniferbusca** [comment]
This is the 4th ticket that has been opened up on this. The first three have been closed without a resolution. The issue has existed for over a year.

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
